<?php

/**
 * resources/templates/os-specific/darwin/sbin/plist/io.appserver.appserver-php5-fpm.plist.phtml
 *
 * PHP version 5
 *
 * @category   Appserver
 * @subpackage Composer
 * @package    TechDivision_ApplicationServer
 * @author     Tim Wagner <tw@techdivision.com>
 * @copyright  2014 TechDivision GmbH <info@techdivision.com>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link       http://www.appserver.io
 */

use AppserverIo\Meta\Composer\Script\Setup;
use AppserverIo\Meta\Composer\Script\SetupKeys;

?>
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd" >
<plist version='1.0'>
    <dict>
        <key>Label</key>
        <string>io.appserver.appserver-php5-fpm</string>
        <key>ProgramArguments</key>
        <array>
            <string><?php echo Setup::getValue(SetupKeys::INSTALL_DIR) ?>/sbin/php-fpm</string>
            <string>--pid=<?php echo Setup::getValue(SetupKeys::INSTALL_DIR) ?>/var/run/appserver-php5-fpm.pid</string>
            <string>--nodaemonize</string>
        </array>
        <key>Debug</key>
        <false/>
        <key>RunAtLoad</key>
        <true/>
        <key>OnDemand</key>
        <false/>
        <key>KeepAlive</key>
        <false/>
	</dict>
</plist>