<?php

/**
 * resources/templates/os-specific/windows/appserverctl-php5-fpm.bat.phtml
 *
 * PHP version 5
 *
 * @category   Appserver
 * @subpackage Composer
 * @package    TechDivision_ApplicationServer
 * @author     Tim Wagner <tw@techdivision.com>
 * @copyright  2014 TechDivision GmbH <info@techdivision.com>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link       http://www.appserver.io
 */

use AppserverIo\Meta\Composer\Script\Setup;
use AppserverIo\Meta\Composer\Script\SetupKeys;

?>
@ECHO OFF
ECHO Starting PHP FastCGI...

set php=php\php-cgi.exe
set ini=php\php.ini

%php% -c %ini% -b <?php echo Setup::getValue(SetupKeys::PHP_FPM_HOST) ?>:<?php echo Setup::getValue(SetupKeys::PHP_FPM_PORT) ?>